site_name: Carl Tsui
nav:
    - Home: index.md
    - c: c/about.md
    - cpp: cpp/about.md
    - rust: rust/about.md
    - golang: golang/about.md
    - python:
        - module: python/module.md
    - shell:
        - dmidecode: shell/dmidecode.md
        - usermod: shell/usermod.md
        - virsh: shell/virsh.md
    - linux: linux/about.md
    - ansible:
        - role: ansible/role.md
        - variable: ansible/variable.md
    - network: network/about.md
    - algorithem: golang/about.md
    - kubernetes:
        - limit: kubernetes/Support.md
        - setup: kubernetes/Setup.md
        - architecture: kubernetes/Architecture of a Kubernetes cluster.md
    - prometheus: prometheus/about.md
    - istio: istio/about.md
theme: readthedocs
